version: '3'
services:
  datascience:
    build: .
    user: root
    ports:
      - "8888:8888"
    volumes:
      - .:/wd
    environment:
      NB_USER: 'enrique'
      JUPYTER_ENABLE_LAB: 'yes'
      GRANT_SUDO: 'yes'
    working_dir: /wd